export const dataDB = [
  {
    brigadeName: "alpha 1",
    brigade_id: "cdsjiocjsdioc",
    battalion: [
      {
        battalionName: "eli_1",
        battalion_id: "djciosjciods",
        means: [
          {
            meansName: "item 1",
            meansType: {
              nameType: "number",
              type_id: "mdlkjcijerdifsoc",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "12",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "item 1",
            meansType: {
              nameType: "string",
              type_id: "jdcisjocijsdi",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "8",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "item 1",
            meansType: {
              nameType: "obg",
              type_id: "sdjiocjsdicjisd",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "mosheCC",
            meansType: {
              nameType: "item 2",
              type_id: "kkopkopopk",
              amount: "10",
              properICT: "10",
              properAmm: "10",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "4",
            comments: "no comments",
          },
          {
            meansName: "gal",
            meansType: {
              nameType: "malnan",
              type_id: "djsiojciosdjc",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "4",
              comments: "no comments",
            },

            totalTypePercent: "4",
            comments: "no comments",
          },
        ],
        percentOfUnit: "50",
        totalSumBattalion: "50",
        comments: "no comments",
      },
      {
        battalionName: "eli_2",
        battalion_id: "idjsciosdjciosd",
        means: [
          {
            meansName: "eli",
            meansType: {
              nameType: "number",
              type_id: "disjciosdjcios",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "12",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "eli",
            meansType: {
              nameType: "string",
              type_id: "dxmkslcwjeoij",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "8",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "eli",
            meansType: {
              nameType: "obg",
              type_id: "jfdlkskcoekdopw",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "mosheCC",
            meansType: {
              nameType: "yahav",
              type_id: "deodkwornfiurh",
              amount: "10",
              properICT: "10",
              properAmm: "10",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "4",
            comments: "no comments",
          },
          {
            meansName: "gal",
            meansType: {
              nameType: "malnan",
              type_id: "ncdushciuerhiuc",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "4",
              comments: "no comments",
            },

            totalTypePercent: "4",
            comments: "no comments",
          },
        ],
        percentOfUnit: "10",
        totalSumBattalion: "10",
        comments: "no comments",
      },
      {
        battalionName: "eli_3",
        battalion_id: "jeoijfierojfioer",
        means: [
          {
            meansName: "avi 2",
            meansType: {
              nameType: "number",
              type_id: "mdsijeiojdewiodjw",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "12",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "avi 2",
            meansType: {
              nameType: "string",
              type_id: "jsiodsjciodjsc",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "8",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "avi 2",
            meansType: {
              nameType: "obg",
              type_id: "zxcvbnm,nbvc",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "mosheCC",
            meansType: {
              nameType: "yahav",
              type_id: "sdiojciosdjcoisdjc",
              amount: "10",
              properICT: "10",
              properAmm: "10",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "4",
            comments: "no comments",
          },
          {
            meansName: "gal",
            meansType: {
              nameType: "malnan",
              type_id: "jfeidcsjiocjsdio",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "4",
              comments: "no comments",
            },

            totalTypePercent: "4",
            comments: "no comments",
          },
        ],
        percentOfUnit: "40",
        totalSumBattalion: "40",
        comments: "no comments",
      },
    ],
    lastUpdateTime: "14-04-2024",
    lastUpdater: "momo",
    totalSumQualification: "40",
    totalViewQualification: [
      {
        meansName: "a",
        meansType: "24",
      },
      {
        meansName: "b",
        meansType: "10",
      },
      {
        meansName: "c",
        meansType: "4",
      },
      {
        meansName: "d",
        meansType: "4",
      },
      {
        meansName: "e",
        meansType: "4",
      },
    ],
    workSpace: "alpha",
    comments: "no comments",
  },
  {
    brigadeName: "alpha",
    brigade_id: "asdfghhjjkll",
    battalion: [
      {
        battalionName: "moshe_1",
        battalion_id: "gfdhfgjfvjdnvjk",
        means: [
          {
            meansName: "nehoray",
            meansType: {
              nameType: "number",
              type_id: "jvhnrttgfjfu",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "12",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "nehoray",
            meansType: {
              nameType: "string",
              type_id: "reiyrereuruieo",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "8",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "nehoray",
            meansType: {
              nameType: "obg",
              type_id: "zxcvbnm,nbvc",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "mosheCC",
            meansType: {
              nameType: "yahav",
              type_id: "dhfgyhygjujyf",
              amount: "10",
              properICT: "10",
              properAmm: "10",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "4",
            comments: "no comments",
          },
          {
            meansName: "gal",
            meansType: {
              nameType: "malnan",
              type_id: "ertyhjknbvc",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "4",
              comments: "no comments",
            },

            totalTypePercent: "4",
            comments: "no comments",
          },
        ],
        percentOfUnit: "50",
        totalSumBattalion: "50",
        comments: "no comments",
      },
      {
        battalionName: "moshe_2",
        battalion_id: "gfdhfgjiwqswoix",
        means: [
          {
            meansName: "nehoray",
            meansType: {
              nameType: "number",
              type_id: "jvhnrttgfjfu",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "12",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "nehoray",
            meansType: {
              nameType: "string",
              type_id: "reiyrereuruieo",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "8",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "nehoray",
            meansType: {
              nameType: "obg",
              type_id: "zxcvbnm,nbvc",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "mosheCC",
            meansType: {
              nameType: "yahav",
              type_id: "dhfgyhygjujyf",
              amount: "10",
              properICT: "10",
              properAmm: "10",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "4",
            comments: "no comments",
          },
          {
            meansName: "gal",
            meansType: {
              nameType: "malnan",
              type_id: "ertyhjknbvc",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "4",
              comments: "no comments",
            },

            totalTypePercent: "4",
            comments: "no comments",
          },
        ],
        percentOfUnit: "10",
        totalSumBattalion: "10",
        comments: "no comments",
      },
      {
        battalionName: "moshe_3",
        battalion_id: "gfdhfgjhsauixmsxk",
        means: [
          {
            meansName: "nehoray",
            meansType: {
              nameType: "number",
              type_id: "jvhnrttgfjfu",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "12",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "nehoray",
            meansType: {
              nameType: "string",
              type_id: "reiyrereuruieo",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "8",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "nehoray",
            meansType: {
              nameType: "obg",
              type_id: "zxcvbnm,nbvc",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "24",
            comments: "no comments",
          },
          {
            meansName: "mosheCC",
            meansType: {
              nameType: "yahav",
              type_id: "dhfgyhygjujyf",
              amount: "10",
              properICT: "10",
              properAmm: "10",
              procent: "4",
              comments: "no comments",
            },
            totalTypePercent: "4",
            comments: "no comments",
          },
          {
            meansName: "gal",
            meansType: {
              nameType: "malnan",
              type_id: "ertyhjknbvc",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "4",
              comments: "no comments",
            },

            totalTypePercent: "4",
            comments: "no comments",
          },
        ],
        percentOfUnit: "40",
        totalSumBattalion: "40",
        comments: "no comments",
      },
    ],
    lastUpdateTime: "14-04-2024",
    lastUpdater: "momo",
    totalSumQualification: "40",
    totalViewQualification: [
      {
        meansName: "a",
        meansType: "24",
      },
      {
        meansName: "b",
        meansType: "10",
      },
      {
        meansName: "c",
        meansType: "4",
      },
      {
        meansName: "d",
        meansType: "4",
      },
      {
        meansName: "e",
        meansType: "4",
      },
    ],
    workSpace: "alpha",
    comments: "no comments",
  },
  {
    brigadeName: "bravo 1",
    brigade_id: "jdisdjioid",
    battalion: [
      {
        battalionName: "charlie_1",
        battalion_id: "djioidsjoij",
        means: [
          {
            meansName: "item 1",
            meansType: {
              nameType: "number",
              type_id: "dskljcsdjcoiew",
              amount: "3",
              properICT: "3",
              properAmm: "3",
              procent: "15",
              comments: "some comments",
            },
            totalTypePercent: "30",
            comments: "some comments",
          },
          {
            meansName: "item 2",
            meansType: {
              nameType: "string",
              type_id: "jdisjciojweof",
              amount: "2",
              properICT: "2",
              properAmm: "2",
              procent: "10",
              comments: "some comments",
            },
            totalTypePercent: "20",
            comments: "some comments",
          },
          {
            meansName: "item 3",
            meansType: {
              nameType: "obg",
              type_id: "dsfiojwjeow",
              amount: "1",
              properICT: "1",
              properAmm: "1",
              procent: "5",
              comments: "some comments",
            },
            totalTypePercent: "10",
            comments: "some comments",
          },
        ],
        percentOfUnit: "30",
        totalSumBattalion: "30",
        comments: "some comments",
      },
      {
        battalionName: "charlie_2",
        battalion_id: "xzcjiowjeio",
        means: [
          {
            meansName: "item 4",
            meansType: {
              nameType: "number",
              type_id: "dksjciojweiof",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "20",
              comments: "some comments",
            },
            totalTypePercent: "40",
            comments: "some comments",
          },
          {
            meansName: "item 5",
            meansType: {
              nameType: "string",
              type_id: "dskjiowjeiof",
              amount: "5",
              properICT: "5",
              properAmm: "5",
              procent: "25",
              comments: "some comments",
            },
            totalTypePercent: "50",
            comments: "some comments",
          },
        ],
        percentOfUnit: "70",
        totalSumBattalion: "70",
        comments: "some comments",
      },
    ],
    lastUpdateTime: "15-04-2024",
    lastUpdater: "mimi",
    totalSumQualification: "60",
    totalViewQualification: [
      { meansName: "a", meansType: "30" },
      { meansName: "b", meansType: "20" },
      { meansName: "c", meansType: "10" },
    ],
    workSpace: "bravo",
    comments: "some comments",
  },
  {
    brigadeName: "charlie 2",
    brigade_id: "efghijkl",
    battalion: [
      {
        battalionName: "delta_1",
        battalion_id: "mnopqrst",
        means: [
          {
            meansName: "item 6",
            meansType: {
              nameType: "number",
              type_id: "uvwxyzab",
              amount: "2",
              properICT: "2",
              properAmm: "2",
              procent: "10",
              comments: "new comments",
            },
            totalTypePercent: "20",
            comments: "new comments",
          },
          {
            meansName: "item 7",
            meansType: {
              nameType: "string",
              type_id: "cdefghij",
              amount: "3",
              properICT: "3",
              properAmm: "3",
              procent: "15",
              comments: "new comments",
            },
            totalTypePercent: "30",
            comments: "new comments",
          },
        ],
        percentOfUnit: "25",
        totalSumBattalion: "25",
        comments: "new comments",
      },
      {
        battalionName: "delta_2",
        battalion_id: "klmnopqr",
        means: [
          {
            meansName: "item 8",
            meansType: {
              nameType: "number",
              type_id: "stuvwxyz",
              amount: "4",
              properICT: "4",
              properAmm: "4",
              procent: "20",
              comments: "new comments",
            },
            totalTypePercent: "40",
            comments: "new comments",
          },
          {
            meansName: "item 9",
            meansType: {
              nameType: "string",
              type_id: "ijklmnop",
              amount: "5",
              properICT: "5",
              properAmm: "5",
              procent: "25",
              comments: "new comments",
            },
            totalTypePercent: "50",
            comments: "new comments",
          },
        ],
        percentOfUnit: "45",
        totalSumBattalion: "45",
        comments: "new comments",
      },
    ],
    lastUpdateTime: "15-04-2024",
    lastUpdater: "mimi",
    totalSumQualification: "50",
    totalViewQualification: [
      { meansName: "x", meansType: "20" },
      { meansName: "y", meansType: "15" },
      { meansName: "z", meansType: "15" },
    ],
    workSpace: "charlie",
    comments: "new comments",
  },
];

export const userDB = {
  FirstName: "moshe",
  PicturURL: "null",
  ProferredName:
    "משה כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר וגיטל/צוות אלפא",
  Title: "סמל",
  WorkEmail: "s86234@army.idf.il",
  userId: "s8624",
  userName: "moshe",
  access: "admin",
};

export const usersListDB = [
  {
    FirstName: "moshe",
    PicturURL: "null",
    ProferredName:
      "משה כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר וגיטל/צוות אלפא",
    Title: "סמל",
    WorkEmail: "s86234@army.idf.il",
    userId: "s8624",
    userName: "moshe",
    access: "editor",
  },
  {
    FirstName: "eli",
    PicturURL: "null",
    ProferredName:
      "משה כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר וגיטל/צוות אלפא",
    Title: "סמל",
    WorkEmail: "s86234@army.idf.il",
    userId: "s8624",
    userName: "eli",
    access: "admin",
  },
  {
    FirstName: "nehoray",
    PicturURL: "null",
    ProferredName:
      "משה כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר וגיטל/צוות אלפא",
    Title: "סמל",
    WorkEmail: "s86234@army.idf.il",
    userId: "s8624",
    userName: "nehoray",
    access: "user",
  },
];
