import { generateID } from "../src/utils/func";

export const dataDB = [
  // {
  //   brigadeName: "alpha 1",
  //   brigade_id: generateID(),
  //   battalion: [
  //     {
  //       battalionName: "eli_1",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "item 1",

  //           nameType: "number",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 12,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "item 1",

  //           nameType: "string",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 8,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "item 1",

  //           nameType: "obg",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "mosheCC",

  //           nameType: "item 2",
  //           type_id: generateID(),
  //           amount: "10",
  //           properICT: "10",
  //           properAmm: "10",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "gal",

  //           nameType: "malnan",
  //           type_id: generateID(),
  //           amount: "4",
  //           properICT: "4",
  //           properAmm: "4",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //       ],
  //       percentOfUnit: "50",
  //       totalSumBattalion: "50",
  //       comments: "no comments",
  //     },
  //     {
  //       battalionName: "eli_2",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "eli",

  //           nameType: "number",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 12,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "eli",

  //           nameType: "string",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 8,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "eli",

  //           nameType: "obg",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "mosheCC",

  //           nameType: "yahav",
  //           type_id: generateID(),
  //           amount: "10",
  //           properICT: "10",
  //           properAmm: "10",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "gal",

  //           nameType: "malnan",
  //           type_id: generateID(),
  //           amount: "4",
  //           properICT: "4",
  //           properAmm: "4",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //       ],
  //       percentOfUnit: "10",
  //       totalSumBattalion: "10",
  //       comments: "no comments",
  //     },
  //     {
  //       battalionName: "eli_3",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "avi 2",

  //           nameType: "number",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 12,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "avi 2",

  //           nameType: "string",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 8,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "avi 2",

  //           nameType: "obg",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "mosheCC",

  //           nameType: "yahav",
  //           type_id: generateID(),
  //           amount: "10",
  //           properICT: "10",
  //           properAmm: "10",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "gal",

  //           nameType: "malnan",
  //           type_id: generateID(),
  //           amount: "4",
  //           properICT: "4",
  //           properAmm: "4",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //       ],
  //       percentOfUnit: "40",
  //       totalSumBattalion: "40",
  //       comments: "no comments",
  //     },
  //   ],
  //   lastUpdateTime: "14-04-2024",
  //   lastUpdater: "momo",
  //   totalSumQualification: "40",
  //   totalViewQualification: [
  //     {
  //       meansName: "a",
  //       procent: 24,
  //     },
  //     {
  //       meansName: "b",
  //       procent: 10,
  //     },
  //     {
  //       meansName: "c",
  //       procent: 4,
  //     },
  //     {
  //       meansName: "d",
  //       procent: 4,
  //     },
  //     {
  //       meansName: "e",
  //       procent: 4,
  //     },
  //   ],
  //   workSpace: "alpha",
  //   comments: "no comments",
  // },
  // {
  //   brigadeName: "alpha",
  //   brigade_id: generateID(),
  //   battalion: [
  //     {
  //       battalionName: "moshe_1",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "nehoray",
  //           type_id: generateID(),

  //           nameType: "number",
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 12,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "nehoray",
  //           type_id: generateID(),

  //           nameType: "string",
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 8,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "nehoray",
  //           type_id: generateID(),

  //           nameType: "obg",
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "mosheCC",
  //           type_id: generateID(),

  //           nameType: "yahav",
  //           amount: "10",
  //           properICT: "10",
  //           properAmm: "10",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "gal",
  //           type_id: generateID(),

  //           nameType: "malnan",
  //           amount: "4",
  //           properICT: "4",
  //           properAmm: "4",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //       ],
  //       percentOfUnit: "50",
  //       totalSumBattalion: "50",
  //       comments: "no comments",
  //     },
  //     {
  //       battalionName: "moshe_2",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "nehoray",

  //           nameType: "number",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 2,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "nehoray",

  //           nameType: "string",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 8,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "nehoray",

  //           nameType: "obg",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "mosheCC",

  //           nameType: "yahav",
  //           type_id: generateID(),
  //           amount: "10",
  //           properICT: "10",
  //           properAmm: "10",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "gal",

  //           nameType: "malnan",
  //           type_id: generateID(),
  //           amount: "4",
  //           properICT: "4",
  //           properAmm: "4",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //       ],
  //       percentOfUnit: "10",
  //       totalSumBattalion: "10",
  //       comments: "no comments",
  //     },
  //     {
  //       battalionName: "moshe_3",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "nehoray",

  //           nameType: "number",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 2,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "nehoray",

  //           nameType: "string",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 8,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "nehoray",

  //           nameType: "obg",
  //           type_id: generateID(),
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "24",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "mosheCC",

  //           nameType: "yahav",
  //           type_id: generateID(),
  //           amount: "10",
  //           properICT: "10",
  //           properAmm: "10",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //         {
  //           meansName: "gal",

  //           nameType: "malnan",
  //           type_id: generateID(),
  //           amount: "4",
  //           properICT: "4",
  //           properAmm: "4",
  //           procent: 4,
  //           comments: "no comments",

  //           totalTypePercent: "4",
  //           comments: "no comments",
  //         },
  //       ],
  //       percentOfUnit: "40",
  //       totalSumBattalion: "40",
  //       comments: "no comments",
  //     },
  //   ],
  //   lastUpdateTime: "14-04-2024",
  //   lastUpdater: "momo",
  //   totalSumQualification: "40",
  //   totalViewQualification: [
  //     {
  //       meansName: "a",
  //       procent: 24,
  //     },
  //     {
  //       meansName: "b",
  //       procent: 10,
  //     },
  //     {
  //       meansName: "c",
  //       procent: 4,
  //     },
  //     {
  //       meansName: "d",
  //       procent: 4,
  //     },
  //     {
  //       meansName: "e",
  //       procent: 4,
  //     },
  //   ],
  //   workSpace: "alpha",
  //   comments: "no comments",
  // },
  // {
  //   brigadeName: "bravo 1",
  //   brigade_id: generateID(),
  //   battalion: [
  //     {
  //       battalionName: "charlie_1",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "item 1",
  //           type_id: generateID(),

  //           nameType: "number",
  //           amount: "3",
  //           properICT: "3",
  //           properAmm: "3",
  //           procent: 15,
  //           comments: "some comments",

  //           totalTypePercent: "30",
  //           comments: "some comments",
  //         },
  //         {
  //           meansName: "item 2",
  //           type_id: generateID(),

  //           nameType: "string",
  //           amount: "2",
  //           properICT: "2",
  //           properAmm: "2",
  //           procent: 10,
  //           comments: "some comments",

  //           totalTypePercent: "20",
  //           comments: "some comments",
  //         },
  //         {
  //           meansName: "item 3",
  //           type_id: generateID(),

  //           nameType: "obg",
  //           amount: "1",
  //           properICT: "1",
  //           properAmm: "1",
  //           procent: 5,
  //           comments: "some comments",

  //           totalTypePercent: "10",
  //           comments: "some comments",
  //         },
  //       ],
  //       percentOfUnit: "30",
  //       totalSumBattalion: "30",
  //       comments: "some comments",
  //     },
  //     {
  //       battalionName: "charlie_2",
  //       battalion_id: generateID(),
  //       means: [
  //         {
  //           meansName: "item 4",
  //           type_id: generateID(),

  //           nameType: "number",
  //           amount: "4",
  //           properICT: "4",
  //           properAmm: "4",
  //           procent: 20,
  //           comments: "some comments",

  //           totalTypePercent: "40",
  //           comments: "some comments",
  //         },
  //         {
  //           meansName: "item 5",
  //           type_id: generateID(),

  //           nameType: "string",
  //           amount: "5",
  //           properICT: "5",
  //           properAmm: "5",
  //           procent: 25,
  //           comments: "some comments",

  //           totalTypePercent: "50",
  //           comments: "some comments",
  //         },
  //       ],
  //       percentOfUnit: "70",
  //       totalSumBattalion: "70",
  //       comments: "some comments",
  //     },
  //   ],
  //   lastUpdateTime: "15-04-2024",
  //   lastUpdater: "mimi",
  //   totalSumQualification: "60",
  //   totalViewQualification: [
  //     { meansName: "a", procent: 30 },
  //     { meansName: "b", procent: 20 },
  //     { meansName: "c", procent: 10 },
  //   ],
  //   workSpace: "bravo",
  //   comments: "some comments",
  // },
  {
    brigadeName: "תטיבת 460",
    brigade_id: generateID(),
    battalion: [
      {
        battalionName: "מפחט",
        battalion_id: generateID(),
        means: [
          {
            meansName: "כלי תקשוב",
            type_id: generateID(),

            nameType: "עננון",
            amount: "1",
            properICT: "1",
            properAmm: "1",
            procent: 12,
            comments: "new comments",

            totalTypePercent: "12",
            comments: "new comments",
          },
          {
            meansName: "כלי תקשוב",
            type_id: generateID(),

            nameType: "פתל",
            amount: "1",
            properICT: "1",
            properAmm: "1",
            procent: 8,
            comments: "new comments",
            totalTypePercent: "8",
          },
          {
            meansName: "כלי תקשוב",
            type_id: generateID(),

            nameType: "רקש 112",
            amount: "1",
            properICT: "1",
            properAmm: "1",
            procent: 4,
            comments: "new comments",
            totalTypePercent: "4",
          },
          {
            meansName: "כלי פיקוד",
            type_id: generateID(),

            nameType: "",
            amount: "10",
            properICT: "10",
            properAmm: "10",
            procent: 4,
            comments: "new comments",
            totalTypePercent: "4",
          },
          {
            meansName: "ערכות שוב נידות",
            type_id: generateID(),

            nameType: "",
            amount: "4",
            properICT: "4",
            properAmm: "",
            procent: 4,
            comments: "new comments",
            totalTypePercent: "4",
          },
          {
            meansName: "סלולר צבאי",
            type_id: generateID(),

            nameType: "",
            amount: "29",
            properICT: "29",
            properAmm: "",
            procent: 4,
            comments: "new comments",
            totalTypePercent: "4",
          },
          {
            meansName: "אטל 2000",
            type_id: generateID(),

            nameType: "",
            amount: "10",
            properICT: "10",
            properAmm: "",
            procent: 4,
            comments: "new comments",
            totalTypePercent: "4",
          },
        ],
        percentOfUnit: "40",
        totalSumBattalion: "40",
        comments: "new comments",
      },
      {
        battalionName: "גדוד 196",
        battalion_id: generateID(),
        means: [
          {
            meansName: "כלי פיקוד",
            type_id: generateID(),
            nameType: "נגמשי מכלול מבצעים",
            amount: "3",
            properICT: "3",
            properAmm: "3",
            procent: 3.6,
            totalTypePercent: "3.6",
            comments: "new comments",
          },
          {
            meansName: "כלי תקשוב",
            type_id: generateID(),
            nameType: "רקש 110",
            amount: "1",
            properICT: "1",
            properAmm: "1",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "ערכות שוב נידות",
            type_id: generateID(),
            nameType: "",
            amount: "11",
            properICT: "11",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "סלולר צבאי",
            type_id: generateID(),
            nameType: "",
            amount: "12",
            properICT: "12",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "אחוזי החזקה חודשים",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 3.6,
            totalTypePercent: "3.6",
            comments: "ציון מה-ASP",
          },
          {
            meansName: "רטל 2000",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "",
          },
        ],
        percentOfUnit: "12",
        totalSumBattalion: "12",
        comments: "new comments",
      },
      {
        battalionName: "גדוד 198",
        battalion_id: generateID(),
        means: [
          {
            meansName: "כלי פיקוד",
            type_id: generateID(),
            nameType: "נגמשי מכלול מבצעים",
            amount: "3",
            properICT: "3",
            properAmm: "3",
            procent: 3.6,
            totalTypePercent: "3.6",
            comments: "new comments",
          },
          {
            meansName: "כלי תקשוב",
            type_id: generateID(),
            nameType: "רקש 110",
            amount: "1",
            properICT: "1",
            properAmm: "1",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "ערכות שוב נידות",
            type_id: generateID(),
            nameType: "",
            amount: "11",
            properICT: "11",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "סלולר צבאי",
            type_id: generateID(),
            nameType: "",
            amount: "12",
            properICT: "12",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "אחוזי החזקה חודשים",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 3.6,
            totalTypePercent: "3.6",
            comments: "ציון מה-ASP",
          },
          {
            meansName: "רטל 2000",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "",
          },
        ],
        percentOfUnit: "12",
        totalSumBattalion: "12",
        comments: "new comments",
      },
      {
        battalionName: "גדוד 532",
        battalion_id: generateID(),
        means: [
          {
            meansName: "כלי פיקוד",
            type_id: generateID(),
            nameType: "נגמשי מכלול מבצעים",
            amount: "3",
            properICT: "3",
            properAmm: "3",
            procent: 3.6,
            totalTypePercent: "3.6",
            comments: "new comments",
          },
          {
            meansName: "כלי תקשוב",
            type_id: generateID(),
            nameType: "רקש 110",
            amount: "1",
            properICT: "1",
            properAmm: "1",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "ערכות שוב נידות",
            type_id: generateID(),
            nameType: "",
            amount: "11",
            properICT: "11",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "סלולר צבאי",
            type_id: generateID(),
            nameType: "",
            amount: "12",
            properICT: "12",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "new comments",
          },
          {
            meansName: "אחוזי החזקה חודשים",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 3.6,
            totalTypePercent: "3.6",
            comments: "ציון מה-ASP",
          },
          {
            meansName: "רטל 2000",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 1.2,
            totalTypePercent: "1.2",
            comments: "",
          },
        ],
        percentOfUnit: "12",
        totalSumBattalion: "12",
        comments: "new comments",
      },
      {
        battalionName: "גדוד 195",
        battalion_id: generateID(),
        means: [
          {
            meansName: "סלולר צבאי",
            type_id: generateID(),
            nameType: "",
            amount: "2",
            properICT: "",
            properAmm: "",
            procent: 1.6,
            totalTypePercent: "1.6",
            comments: "new comments",
          },
          {
            meansName: "אחוזי החזקה חודשים",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 4.8,
            totalTypePercent: "4.8",
            comments: "ציון מה-ASP",
          },
          {
            meansName: "אטל 2000",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 1.6,
            totalTypePercent: "1.6",
            comments: "",
          },
        ],
        percentOfUnit: "8",
        totalSumBattalion: "8",
        comments: "new comments",
      },
      {
        battalionName: "גדוד 183",
        battalion_id: generateID(),
        means: [
          {
            meansName: "סלולר צבאי",
            type_id: generateID(),
            nameType: "",
            amount: "2",
            properICT: "",
            properAmm: "",
            procent: 1.6,
            totalTypePercent: "1.6",
            comments: "new comments",
          },
          {
            meansName: "אחוזי החזקה חודשים",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 4.8,
            totalTypePercent: "4.8",
            comments: "ציון מה-ASP",
          },
          {
            meansName: "אטל 2000",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 1.6,
            totalTypePercent: "1.6",
            comments: "",
          },
        ],
        percentOfUnit: "6",
        totalSumBattalion: "6",
        comments: "new comments",
      },
      {
        battalionName: "יחסם",
        battalion_id: generateID(),
        means: [
          {
            meansName: "כלי תקשוב",
            type_id: generateID(),
            nameType: "נגמשי פיקוד",
            amount: "1",
            properICT: "1",
            properAmm: "1",
            procent: 3,
            totalTypePercent: "3",
            comments: "new comments",
          },
          {
            meansName: "כלי פיקוד",
            type_id: generateID(),
            nameType: "אמר מפקד פתן , נגמשי מפ אבטחה , נגמשי רפואה",
            amount: "3",
            properICT: "3",
            properAmm: "3",
            procent: 3,
            totalTypePercent: "3",
            comments: "",
          },
          {
            meansName: "אחוזי אבטחה חודשיים",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 3,
            totalTypePercent: "3",
            comments: "ציון מה - SAP",
          },
          {
            meansName: "אטל 2000",
            type_id: generateID(),
            nameType: "",
            amount: "",
            properICT: "",
            properAmm: "",
            procent: 1,
            totalTypePercent: "1",
            comments: "",
          },
        ],
        percentOfUnit: "10",
        totalSumBattalion: "10",
        comments: "new comments",
      },
    ],
    lastUpdateTime: "15-04-2024",
    lastUpdater: "mimi",
    totalSumQualification: "92",
    totalViewQualification: [
      { meansName: "כלי תקשוב", procent: 30 },
      { meansName: "כלי פיקוד", procent: 16 },
      { meansName: "ערכות שוב נידות", procent: 7 },
      { meansName: "סלולר צבאי", procent: 9 },
      { meansName: "אטל 2000", procent: 7 },
      { meansName: "אחוזי החזקה חודשים", procent: 17 },
      { meansName: "רטל 2000", procent: 3 },
      { meansName: "אחוזי אבטחה חודשיים", procent: 3 },
    ],
    workSpace: "charlie",
    comments: "new comments",
  },
];

export const userDB = {
  FirstName: "moshe",
  LastName: "moshe",
  // PicturURL: "https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg",
  PicturURL:
    "https://play-lh.googleusercontent.com/S4wylkvt2jz16hnG9IG0pAZosbB82nWWy8P-rQkb54uH-SCVd5L2j7z7x1Vz5pZvIRc",
  ProferredName:
    "משה כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר ודיגיטל/צוות אלפא",
  Title: "סמל",
  WorkEmail: "s86234@army.idf.il",
  userId: generateID(),
  userName: "moshe",
  access: "admin",
};
export const usersListDB = [
  {
    FirstName: "moshe",
    LastName: "moshe",
    PicturURL:
      "https://play-lh.googleusercontent.com/S4wylkvt2jz16hnG9IG0pAZosbB82nWWy8P-rQkb54uH-SCVd5L2j7z7x1Vz5pZvIRc",
    ProferredName: "משה כהן -פיקוד ההכשרות והאימונים/מקשא''פ/צוות אלפא",
    Title: "סמל",
    WorkEmail: "s86234@army.idf.il",
    userId: generateID(),
    userName: "moshe",
    access: "admin",
  },
  {
    FirstName: "eli",
    LastName: "rozi",
    PicturURL:
      "https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg",
    ProferredName:
      "אלי כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר וגיטל/צוות אלפא",
    Title: "סמל",
    WorkEmail: "s86234@army.idf.il",
    userId: generateID(),
    userName: "eli",
    access: "admin",
  },
  {
    FirstName: "nehoray",
    LastName: "moshe",
    PicturURL:
      "https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg",
    ProferredName:
      "נהוראי כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר וגיטל/צוות אלפא",
    Title: "סמל",
    WorkEmail: "s86234@army.idf.il",
    userId: generateID(),
    userName: "nehoray",
    access: "user",
  },
  {
    FirstName: "nehoray",
    LastName: "moshe",
    PicturURL:
      "https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg",
    ProferredName:
      "נהוראי כהן -פיקוד ההכשרות והאימונים/מקשא''פ/מדור לומ''ר וגיטל/צוות אלפא",
    Title: "סמל",
    WorkEmail: "s86234@army.idf.il",
    userId: generateID(),
    userName: "nehoray",
    access: "user",
  },
];
